# Generated by Django 6.0.4 on 2026-05-10 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('Car Suspension', 'Car Suspension'), ('Car Engine', 'Car Engine'), ('Engine Oil Service', 'Engine Oil Service'), ('Engine Scan', 'Engine Scan'), ('Break Disc', 'Break Disc'), ('Electrical Works', 'Electrical Works')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.TextField()),
                ('product_picture', models.ImageField(upload_to='product_picture/')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_discount', models.CharField(max_length=20)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
