# Generated by Django 6.0.2 on 2026-02-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp1', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='message',
            new_name='address',
        ),
    ]
