# Generated by Django 6.0.2 on 2026-02-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='namwe',
            new_name='name',
        ),
    ]
