s = ("Tos technlogy")

print(s.capitalize())
print(s.casefold())
print(s.count('o'))
print(s.center(40, '='))
print(s.startswith('To'))
print(s.endswith('gy'))
print(s.find('chn'))
print(s.index('t',1))
print("top123".isalnum())
print("123".isalnum())
print('a1213'.isnumeric())
print(' '.isspace())
print("hello".replace('e','b'))
