# Generated by Django 6.0.2 on 2026-02-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_message_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pricture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pricture'),
        ),
    ]
