# Generated by Django 6.0.2 on 2026-02-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('all-colection', 'all-colection'), ('mobile', 'Mobile'), ('camera', 'Camera'), ('headphone', 'Headphone'), ('laptop', 'Laptop'), ('speakers', 'Speakers')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_desc', models.TextField()),
                ('profile_pricture', models.ImageField(upload_to='profile_pricture')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
